version: "3.9"

networks:
  cluster:

services:
  redis-master:
    image: redis:6-alpine
    networks:
      - cluster
  
  redis-slave:
    image: redis:6-alpine
    networks:
      - cluster
    depends_on:
      - redis-master
    command: redis-server --slaveof redis-master 6379

  redis-sentinel:
    image: redis:6-sential
    networks:
      - cluster
    depends_on:
      - redis-master
      - redis-slave
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
      - REDIS_MASTER=redis-master