basePath: /api/v1
definitions:
  main.Hreq:
    properties:
      name:
        type: string
    type: object
  main.Hres:
    properties:
      code:
        type: string
    type: object
info:
  contact: {}
paths:
  /example/helloworld:
    get:
      consumes:
      - application/json
      description: do ping
      parameters:
      - description: '-'
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/main.Hreq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Hres'
      summary: ping example
      tags:
      - example
swagger: "2.0"
